name: t00ls-sign

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
    - name: py
      run: python TuBi.py
      env:
        TUBI_USERNAME: ${{ secrets.TUBI_USERNAME }}
        TUBI_PASSWORD: ${{ secrets.TUBI_PASSWORD }}
        TUBI_QUESTION_NUM: ${{ secrets.TUBI_QUESTION_NUM }}
        TUBI_QUESTION_ANSWER: ${{ secrets.TUBI_QUESTION_ANSWER }}
